### ISSUE TITLE
Win Analog won't download

### ISSUE THREAD

**Issue by donmac2** [c-amie/analog-ce#7]
If I try to download the Windows precompiled binary for Analog CE 6.0.18, I get: 
Microsoft OLE DB Provider for ODBC Drivers error '80004005'

[Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified

/api/import/elara/elara/MySqlDbConn.class.asp, line 155

Thank you for maintaining Analog,

Don Macnaughton  donmac@matstat.com

**Comment by c-amie** [comment]
Blast, sorry about that. Driver problems. It is now fixed.
